version: '3'
services:
  proxy:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./data/html:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress
  
  mysql:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: mydatabase
    volumes:
      - mdb:/var/lib/mysql

  wordpress:
    image: wordpress:fpm-alpine
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: root-password
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: mydatabase
    volumes:
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php
      - ./wordpress/wp-content:/var/www/html/wp-content
    links:
      - mysql

volumes:
  mdb:
    driver: local
    driver_opts:
      type: none
      device: "./mdb"
      o: bind
